name: Publish tag
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1
        with:
          registry: registry.hotellistat.com
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            registry.hotellistat.com/oss/amps:latest
            registry.hotellistat.com/oss/amps:${{ steps.tag.outputs.tag }}
            ghcr.io/hotellistat/amps
            ghcr.io/hotellistat/amps:${{ steps.tag.outputs.tag }}
