name: Publish app
on:
  push:
    branches:
      - main
    paths:
      - "cmd/**/*"
  workflow_dispatch:
jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: registry.hotellistat.com
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            registry.hotellistat.com/oss/amps:latest
            registry.hotellistat.com/oss/amps:${{ github.sha }}