name: Publish app
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: actions/download-artifact@v2
      - uses: docker/login-action@v1
        with:
          registry: registry.hotellistat.com
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - id: image-tag
        run: |
          sha="${{ github.sha }}"
          id="${sha:0:8}"
          echo "::set-output name=id::$id"

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: registry.hotellistat.com/oss/batchable:latest,registry.hotellistat.com/oss/batchable:${{steps.image-tag.outputs.id}}
