name: Publish app
on:
  push:
    branches:
      - main
    paths:
      - "cmd/**/*"
  workflow_dispatch:
jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: registry.hotellistat.com
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            registry.hotellistat.com/oss/amps:latest
            registry.hotellistat.com/oss/amps:${{ github.sha }}
            ghcr.io/hotellistat/amps
            ghcr.io/hotellistat/amps:${{ github.sha }}
